name: Build and Release ADB Optimizer

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install pyinstaller PySide6

    - name: Build with PyInstaller
      run: |
        pyinstaller --name adb-optimizer --onefile main.py

    - name: Package output
      run: |
        mkdir output
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mv dist/adb-optimizer.exe output/
          powershell Compress-Archive -Path output/adb-optimizer.exe -DestinationPath adb-optimizer-windows.zip
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          mv dist/adb-optimizer output/adb-optimizer-macos
          chmod +x output/adb-optimizer-macos
          tar -czf adb-optimizer-macos.tar.gz -C output adb-optimizer-macos
        else
          mv dist/adb-optimizer output/adb-optimizer-linux
          chmod +x output/adb-optimizer-linux
          tar -czf adb-optimizer-linux.tar.gz -C output adb-optimizer-linux
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: |
          *.zip
          *.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-release-${{ github.run_number }}
        name: ADB Optimizer ${{ github.run_number }}
        body: |
          自動打包發布的版本（帶終端）：
          - Windows: adb-optimizer-windows.zip
          - macOS: adb-optimizer-macos.tar.gz
          - Linux: adb-optimizer-linux.tar.gz
        files: |
          dist/**/*.zip
          dist/**/*.tar.gz
