name: Build and Release Qt Python App

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install pyinstaller PySide6

    - name: Build with PyInstaller
      run: |
        pyinstaller --name adb-optimizer --onefile --noconsole main.py

    - name: Rename output file
      run: |
        mkdir output
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          mv dist/adb-optimizer.exe output/adb-optimizer-windows.exe
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          mv dist/adb-optimizer output/adb-optimizer-macos
        else
          mv dist/adb-optimizer output/adb-optimizer-linux
        fi
      shell: bash

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-${{ matrix.os }}
        path: output/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: auto-release-${{ github.run_number }}
        name: Release Build ${{ github.run_number }}
        body: |
          自動從 main 分支編譯並打包的 Qt 應用程式。
          包含三個平台版本（Windows、macOS、Linux）。
        files: |
          dist/**/*

