name: Pylint + Reviewdog PR Comment

on:
  pull_request:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint and save report
      run: |
        pylint **/*.py --output-format=text > pylint_report.txt || true

    - name: Install reviewdog CLI
      run: |
        curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin latest
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Run reviewdog to comment PR
      run: |
        reviewdog \
          -f=pylint \
          -name="pylint" \
          -reporter=github-pr-review \
          -level=warning \
          -fail-on-error=false \
          -filter-mode=diff_context < pylint_report.txt
