name: Pylint with reviewdog

on:
  pull_request:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint and annotate PR with reviewdog
      id: reviewdog
      run: |
        pylint **/*.py --output-format=text > pylint_report.txt || true
      continue-on-error: true

    - name: reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        filter_mode: diff_context
        fail_on_error: false
        level: warning
        name: pylint
        # pylint 使用 eslint 格式解析，输入从上一步保存的文件传递
        # reviewdog-action 目前不支持直接文件输入，这里用 workaround
        # 参考：https://github.com/reviewdog/action-eslint/issues/28
        # 所以这里演示基础用法，需要配合后续改进
