name: Pylint + Reviewdog PR Comment

on:
  pull_request:
    branches: [main]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install pylint
        run: pip install pylint

      - name: Run pylint with checkstyle output
        run: |
          pylint . --output-format=checkstyle > pylint_report.xml || true
          echo "pylint output preview:"
          head -40 pylint_report.xml

      - name: Install reviewdog CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b $HOME/bin latest
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run reviewdog to comment PR
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -f=checkstyle -reporter=github-pr-review -level=warning -fail-on-error=false -filter-mode=diff_context < pylint_report.xml
